version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'

  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'docker'
    directories:
      - '/contexts/*/'
    groups:
      arcane:
        patterns:
          - 'getarcaneapp/*'
    schedule:
      interval: 'daily'
