version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'

  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
    schedule:
      interval: 'weekly'
      day: 'monday'

  - package-ecosystem: 'docker'
    directories:
      - '/contexts/*/'
    groups:
      arcane:
        patterns:
          - 'getarcaneapp/*'
      formbricks:
        patterns:
          - 'formbricks/*'
      n8n:
        patterns:
          - 'n8nio/n8n'
          - 'n8nio/runners'
      n8n-sandbox-service:
        patterns:
          - 'n8nio/n8n-sandbox-service-*'
      plane:
        patterns:
          - 'makeplane/*'
    schedule:
      interval: 'daily'
