[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[env]
_.file = [".env"]
_.path = ["{{config_root}}/node_modules/.bin"]
PNPM_CONFIG_STORE_DIR = "~/.local/share/pnpm/store"

[tools]
hadolint = "latest"

[tasks.install]
description = "Install dependencies"
depends = ["pnpm-install"]

[tasks.pnpm-install]
description = "Install Node.js packages"
run = "pnpm install"
sources = ["mise.toml", "package.json", "pnpm-lock.yaml"]
outputs = ["node_modules/.pnpm/lock.yaml"]
