FROM geerlingguy/docker-ubuntu2604-ansible:latest@sha256:fb716fe466d3e9dcec17c3e04f78c6ef3b4c4a1cbf00f1df8a6a72df913e3ce0

# Add the official Docker APT repository
ADD --chmod=644 https://download.docker.com/linux/ubuntu/gpg /etc/apt/keyrings/docker.asc

COPY <<EOF /etc/apt/sources.list.d/docker.sources
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: noble
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

# Install Docker CE to allow Ansible to manage containers during testing
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
      containerd.io \
      docker-buildx-plugin \
      docker-ce \
      docker-ce-cli \
      docker-compose-plugin \
  && rm -Rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Install Python dependencies required for Ansible to manage Docker during testing
RUN pip3 install --no-cache-dir docker jsondiff
