FROM geerlingguy/docker-ubuntu2404-ansible:latest@sha256:18bf80157ea24b3210eb25ca89a5460912271b0ee61f238f36d2b115c89e39e6

# Install Docker inside the container to allow Ansible to manage Docker containers during testing
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io docker-compose-v2 \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Install Python dependencies required for Ansible to manage Docker during testing
RUN pip3 install --no-cache-dir docker jsondiff
