FROM geerlingguy/docker-ubuntu2404-ansible:latest@sha256:8c3395f40c45edd96e7267cde639d2900cf5b2f73d9b903fd703322486e10cf9

# Install Docker inside the container to allow Ansible to manage Docker containers during testing
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io docker-compose-v2 \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Install Python dependencies required for Ansible to manage Docker during testing
RUN pip3 install --no-cache-dir docker jsondiff
