FROM geerlingguy/docker-ubuntu2604-ansible:latest@sha256:fb716fe466d3e9dcec17c3e04f78c6ef3b4c4a1cbf00f1df8a6a72df913e3ce0

# Install Docker inside the container to allow Ansible to manage Docker containers during testing
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io docker-compose-v2 \
    && apt-get clean \
    && rm -Rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Install Python dependencies required for Ansible to manage Docker during testing
RUN pip3 install --no-cache-dir docker jsondiff
