FROM geerlingguy/docker-ubuntu2404-ansible:latest@sha256:bab98bf6bf4b65908a5cf46a08a9a20c95916c500e83894b5f63a82f1305a778

# Add the official Docker APT repository
ADD --chmod=644 https://download.docker.com/linux/ubuntu/gpg /etc/apt/keyrings/docker.asc

COPY <<EOF /etc/apt/sources.list.d/docker.sources
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: noble
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

# Install Docker CE to allow Ansible to manage containers during testing
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
      containerd.io \
      docker-buildx-plugin \
      docker-ce \
      docker-ce-cli \
      docker-compose-plugin \
  && rm -Rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# Install Python dependencies required for Ansible to manage Docker during testing
RUN pip3 install --no-cache-dir docker jsondiff
