FROM ghcr.io/skriptfabrik/fileenv:1.1.0 AS fileenv

FROM n8nio/n8n-sandbox-service-api:1.1.1

COPY --from=fileenv /usr/local/bin/fileenv /usr/local/bin/fileenv

ENTRYPOINT ["/usr/local/bin/fileenv", "/usr/local/bin/sandbox-api"]
