name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint commit messages
        run: |
          pnpm commitlint \
            --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
            --to ${{ github.event.pull_request.head.sha }}
          echo "Commit messages linting passed"

  diff:
    name: Diff Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      build-matrix-json: ${{ steps.diff.outputs.build-matrix-json }}
      docker-files: ${{ steps.diff.outputs.docker-files }}
      prettier-files: ${{ steps.diff.outputs.prettier-files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Diff against base branch
        id: diff
        run: |
          git fetch --quiet origin ${{ github.event.pull_request.base.ref }}
          base_sha=$(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }})
          # We use the base SHA here, not the PR head SHA, because this workflow is triggered by a pull_request event, not a push event.
          changed_files=$(git diff --name-only --diff-filter=AM $base_sha ${{ github.event.pull_request.head.sha }})
          if [ -z "$changed_files" ]; then
            echo "::group::No changes detected"
            echo "::endgroup::"
          else
            echo "::group::Changed files:"
            echo "$changed_files"
            echo "::endgroup::"
          fi
          # We detect changes in files that should be checked with Prettier (JavaScript, TypeScript, JSON, Markdown, YAML).
          prettier_files=$(echo "$changed_files" | grep -E '\.(c?js|mjs|json|md|ya?ml)$' || true)
          if [ -z "$prettier_files" ]; then
            echo "::group::No changes in files to check with Prettier detected"
            echo "::endgroup::"
          else
            echo "::group::Changed files to check with Prettier:"
            echo "$prettier_files"
            echo "::endgroup::"
          fi
          # We detect changes in Dockerfiles, which should be checked with Hadolint.
          docker_files=$(echo "$changed_files" | grep -E 'Dockerfile(\..+)?$' || true)
          if [ -z "$docker_files" ]; then
            echo "::group::No changes in Docker files detected"
            echo "::endgroup::"
          else
            echo "::group::Changed Docker files:"
            echo "$docker_files"
            echo "::endgroup::"
          fi
          # We only want to build images for contexts that have changed.
          docker_contexts=$(echo "$changed_files" | grep -Eo '^contexts/[^/]+' | sed 's|^contexts/||' | sort -u || true)
          if [ -z "$docker_contexts" ]; then
            build_matrix_json='[]'
            echo "::group::No changes in Docker contexts detected"
            echo "::endgroup::"
            echo "::group::No build matrix generated"
            echo "::endgroup::"
          else
            build_matrix_json=$(jq -c --argjson images "$(jq '.images' images.json)" --arg docker_contexts "$docker_contexts" -n '
              ($docker_contexts | split("\n") | map(select(length > 0))) as $changed
              | $images | map(select(.context as $c | $changed | index($c) != null))
            ')
            echo "::group::Changed Docker contexts:"
            echo "$docker_contexts"
            echo "::endgroup::"
            echo "::group::Build matrix"
            echo "$build_matrix_json" | jq .
            echo "::endgroup::"
          fi
          # We output the results to be used in the next jobs.
          echo "build-matrix-json=$build_matrix_json" >> $GITHUB_OUTPUT
          echo "docker-files=$(echo "$docker_files" | xargs | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "prettier-files=$(echo "$prettier_files" | xargs | tr -d '\n')" >> $GITHUB_OUTPUT

  build:
    name: Build Docker Image (${{ matrix.name }})
    needs: diff
    if: ${{ needs.diff.outputs.build-matrix-json != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.diff.outputs.build-matrix-json) }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract version
        id: extract_version
        run: echo "version=$(grep -m 1 'FROM ${{ matrix.base }}' 'contexts/${{ matrix.context }}/${{ matrix.file }}' | cut -d':' -f2- | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: skriptfabrik/github-actions/build-docker-image@main
        with:
          context: contexts/${{ matrix.context }}
          file: ${{ matrix.file }}
          name: ${{ matrix.name }}
          push: false

  hadolint:
    name: Lint Dockerfiles
    needs: diff
    if: ${{ needs.diff.outputs.docker-files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Hadolint
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0

      - name: Lint Dockerfiles with Hadolint
        run: hadolint $(echo "${{ needs.diff.outputs.docker-files }}" | xargs)

  prettier:
    name: Lint Prettier Files
    needs: diff
    if: ${{ needs.diff.outputs.prettier-files != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint files with Prettier
        run: pnpm prettier --check $(echo "${{ needs.diff.outputs.prettier-files }}" | xargs)
